services:
  backend:
    build: ./backend
    container_name: backend
    env_file: .env
    restart: always
    networks:
      - webnet

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    networks:
      - webnet

  caddy:
    image: caddy:2
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - webnet
    depends_on:
      - backend
      - frontend

networks:
  webnet:

volumes:
  caddy_data:
  caddy_config:
